name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1: Build
  build:
    name: 🛠️ Build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

        
  deploy:
    name: 🚀 Deploy
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove existing app container if exists
        run: docker rm -f springboot_tasklist_app || true

      - name: Run Spring Boot App Container
        run: |
          docker run -d \
            --name springboot_tasklist_app \
            --network spring_network \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://taskdb_db:5432/${{ secrets.DB_NAME }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e SERVER_PORT=${{ secrets.APP_PORT }} \
            -p ${{ secrets.APP_PORT }}:${{ secrets.APP_PORT }} \
            ${{ secrets.DOCKER_USERNAME }}/springboot_tasklist_app:latest

      - name: Prepare deployment folder
        run: |
          if [ ! -d "$HOME/tasklist" ]; then
            echo "Folder ~/tasklist not found. Cloning fresh copy..."
            git clone https://github.com/${{ github.repository }} ~/tasklist
          else
            echo "Folder exists. Pulling latest changes..."
            cd ~/tasklist
            git pull origin main
          fi

      - name: Create .env file in deployment folder
        run: |
          cat <<EOF > ~/tasklist/.env
          POSTGRES_VERSION=17
          POSTGRES_DB=${{ secrets.DB_NAME }}
          POSTGRES_USER=${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
          POSTGRES_PORT=5432
          APP_PORT=${{ secrets.VM_PORT }}
          DB_URL=jdbc:postgresql://${{ secrets.HOST_IP }}:5432/${{ secrets.DB_NAME }}
          EOF

      - name: Run Spring Boot directly on VM (optional)
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://${{ secrets.HOST_IP }}:5432/${{ secrets.DB_NAME }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SERVER_PORT: ${{ secrets.VM_PORT }}
        run: |
          cd ~/tasklist
          nohup mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=${SERVER_PORT}" > vm_app.log 2>&1 &


  # Job 2: Test
  test:
    name: ✅ Test with PostgreSQL
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean up previous containers
        run: |
          docker rm -f taskdb_db springboot_tasklist_app || true

      - name: Create Docker network
        run: |
          docker network create spring_network || true

      - name: Run PostgreSQL Container
        run: |
          docker volume create postgres_data || true
          docker run -d \
            --name taskdb_db \
            --network spring_network \
            -v postgres_data:/var/lib/postgresql/data \
            -e POSTGRES_DB=${{ secrets.DB_NAME }} \
            -e POSTGRES_USER=${{ secrets.DB_USERNAME }} \
            -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -p 5432:5432 \
            postgres:17

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            if docker exec taskdb_db pg_isready -U ${{ secrets.DB_USERNAME }} > /dev/null; then
              echo "PostgreSQL is ready!"
              break
            else
              echo "Waiting... ($i)"
              sleep 2
            fi
          done

      - name: Test with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ secrets.DB_NAME }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          APP_PORT: ${{ secrets.APP_PORT }}
        run: |
          mvn test -Dspring-boot.run.arguments="--server.port=${APP_PORT}"
