name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Log in to Docker Hub
        if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Test with Maven
        run: |
          mvn clean package -DskipTests=false
          mvn test
          
      - name: Prepare deployment folder
        run: |
          if [ ! -d "$HOME/tasklist" ]; then
            echo "Folder ~/tasklist not found. Cloning fresh copy..."
            git clone https://github.com/${{ github.repository }} ~/tasklist
          else
            echo "Folder exists. Pulling latest changes..."
            cd ~/tasklist
            git pull origin main
          fi

      - name: Deploy Spring Boot app with Docker Compose
        run: |
          cd ~/tasklist
          echo "Stopping old containers..."
          docker compose down || true

          echo "Rebuilding and starting containers..."
          docker compose up -d --build

          echo "Deployment complete!"

      - name: Push image to Docker Hub
        if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
        run: |
          echo "Tagging image..."
          docker tag tasklist_app:latest ${{ secrets.DOCKER_USERNAME }}/tasklist:latest
          echo "Pushing to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/tasklist:latest
