name: Build, Test, and Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: Run tests
        run: mvn test

      - name: Deploy Spring Boot App with Docker Compose
        run: |
          echo "Navigating to project folder..."
          cd ~/tasklist || { echo "Directory missing!"; exit 1; }

          echo "Stopping existing containers..."
          docker compose down || true

          echo "Starting containers..."
          docker compose up -d --build

          echo "Deployment complete!"
