name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'



      - name: Push image to Docker Hub
        if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
        run: |
          echo "Tagging image..."
          docker tag tasklist_app:latest ${{ secrets.DOCKER_USERNAME }}/tasklist:latest
          echo "Pushing to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/tasklist:latest
